# Generated by Django 2.2.5 on 2019-10-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commands',
            old_name='data2',
            new_name='Command',
        ),
    ]
