# Generated by Django 2.2.5 on 2019-10-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20191028_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commands',
            old_name='Command',
            new_name='command',
        ),
        migrations.AddField(
            model_name='commands',
            name='lesson',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
