# Generated by Django 2.2.5 on 2019-10-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191029_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commands',
            old_name='command',
            new_name='command1',
        ),
        migrations.AddField(
            model_name='commands',
            name='command2',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
