# Generated by Django 2.2.5 on 2019-10-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commands',
            name='command2',
        ),
    ]
