# Generated by Django 2.2.5 on 2019-10-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_commands_command2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commands',
            name='command1',
        ),
    ]
