# Generated by Django 2.2.5 on 2019-10-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_commands_command1'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='command1',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
